CREATE DATABASE sample;

USE sample;

CREATE TABLE BATCH_SAMPLE (
	 id bigint not null  primary key , 
	 content VARCHAR(100) not null,
	 version INT not null, 
	 -- queued_id VARCHAR(100) not null,
	 -- queued_ts TIMESTAMP not null DEFAULT CURRENT_TIMESTAMP
); 


INSERT INTO BATCH_SAMPLE (ID, CONTENT, VERSION) VALUES (0, 'A', 0);
INSERT INTO BATCH_SAMPLE (ID, CONTENT, VERSION) VALUES (1, 'B', 0);
INSERT INTO BATCH_SAMPLE (ID, CONTENT, VERSION) VALUES (2, 'C', 0);
INSERT INTO BATCH_SAMPLE (ID, CONTENT, VERSION) VALUES (3, 'D', 0);
INSERT INTO BATCH_SAMPLE (ID, CONTENT, VERSION) VALUES (4, 'E', 0);
INSERT INTO BATCH_SAMPLE (ID, CONTENT, VERSION) VALUES (5, 'F', 0);
INSERT INTO BATCH_SAMPLE (ID, CONTENT, VERSION) VALUES (6, 'G', 0);
INSERT INTO BATCH_SAMPLE (ID, CONTENT, VERSION) VALUES (7, 'H', 0);
INSERT INTO BATCH_SAMPLE (ID, CONTENT, VERSION) VALUES (8, 'I', 0);
INSERT INTO BATCH_SAMPLE (ID, CONTENT, VERSION) VALUES (9, 'J', 0);


COMMIT;